import {
  RefreshCw, CalendarPlus, Building2, Gauge, Bell, Users, Truck, ClipboardCheck, ShieldCheck,
  History, Printer, Download, Mail, Share2, Pencil, IdCard, XCircle, Award, LayoutGrid,
  Receipt, CreditCard, FilterX, UserPlus, Lock, UserX, Car, Network, CarFront, UsersRound,
  BadgeCheck, CalendarClock, Upload, Wrench, AlertTriangle, RotateCcw, Eye, CircleAlert,
  CheckSquare, ArrowUp, MessageSquare, X, CalendarDays, Repeat, FileCheck2, Search, Filter,
  Calendar, User, FileText, SlidersHorizontal, Palette, Globe, Plug, KeyRound, Smartphone,
  Database, PanelLeft, Rows3, Columns3, ChevronsUp, Maximize, Settings, Info, Clock,
  TrendingUp, PieChart, BarChart3, Percent, Trash2, Files, Play, Package, CheckCircle2,
  Route, MapPin, Fuel, CircleDot, Ruler, Coins, Wallet, Scale, ShoppingCart, PackageCheck,
  PackageMinus, Send, Banknote, CircleDollarSign, ShieldAlert, HeartPulse, Radio,
  Signal, Zap, Landmark, Timer, Server, UserCog, Boxes, FileWarning, ClipboardList, Undo2,
} from 'lucide-react';

/* ══════════════════════════════════════════════════════════════
   One tenant's workspace: every tab works this company's own
   fleet, people and sheets. There is no cross-company view.
   ══════════════════════════════════════════════════════════════ */

export const TABS = [
  { key: 'dashboard', label: 'Dashboard' },
  { key: 'fleet', label: 'Fleet' },
  { key: 'users', label: 'Operators' },
  { key: 'dispatch', label: 'Dispatch' },
  { key: 'inspections', label: 'Inspections' },
  { key: 'workshop', label: 'Workshop' },
  { key: 'parts', label: 'Parts' },
  { key: 'tyres', label: 'Tyres' },
  { key: 'fuel', label: 'Fuel' },
  { key: 'telematics', label: 'Telematics' },
  { key: 'compliance', label: 'Compliance' },
  { key: 'documents', label: 'Documents' },
  { key: 'incidents', label: 'Incidents' },
  { key: 'costs', label: 'Costs' },
  { key: 'procurement', label: 'Procurement' },
  { key: 'billing', label: 'Billing' },
  { key: 'contracts', label: 'Contracts' },
  { key: 'reports', label: 'Reports' },
  { key: 'analytics', label: 'Analytics' },
  { key: 'admin', label: 'Admin' },
  { key: 'hierarchy', label: 'Hierarchy' },
  { key: 'audit', label: 'Audit log' },
  { key: 'profile', label: 'Company' },
  { key: 'settings', label: 'Settings' },
  { key: 'view', label: 'View' },
];

export const CTX = {
  inspections: ['Inspection tools', 'Pre-use sheets'],
  fleet: ['Vehicle tools', 'Fleet register'],
  workshop: ['Workshop tools', 'Job cards'],
  users: ['Operator tools', 'People'],
  dispatch: ['Dispatch tools', 'Haulage jobs'],
  parts: ['Stores tools', 'Inventory'],
  tyres: ['Tyre tools', 'Tyre register'],
  fuel: ['Fuel tools', 'Transactions'],
  telematics: ['Telematics tools', 'Units and events'],
  compliance: ['Safety tools', 'Certificates'],
  documents: ['Document tools', 'Register'],
  incidents: ['Incident tools', 'Investigations'],
  costs: ['Cost tools', 'Cost control'],
  procurement: ['Procurement tools', 'Orders and invoices'],
  billing: ['Billing tools', 'Customer invoices'],
  contracts: ['Asset tools', 'Finance and leases'],
  admin: ['Administration', 'Platform'],
  profile: ['Company tools', 'Acme Mining Corp'],
};

export const RIBBON = {
  dispatch: [
    { label: 'Jobs', lg: [[Route, 'Plan a\njob', 'dlg:planJob'], [Play, 'Dispatch', 'jobStatus:In transit']], sm: [[CheckCircle2, 'Mark delivered', 'jobStatus:Delivered'], [X, 'Cancel the job', 'jobStatus:Cancelled'], [FileCheck2, 'Capture the POD', 'recordPod']] },
    { label: 'Planning', lg: [[MapPin, 'Plan\nboard', 'dispatchView:board'], [Percent, 'Lane\nprofitability', 'dispatchView:lanes']], sm: [[Truck, 'Open the vehicle', 'openJobVehicle'], [User, 'Open the operator', 'openJobDriver'], [Radio, 'Track it', 'goto:telematics']] },
    { label: 'Revenue', lg: [[Receipt, 'Raise an\ninvoice', 'raiseInvoice']], sm: [[CircleDollarSign, 'Ready to bill', 'goto:billing'], [Banknote, 'Rate card', 'rateCard']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe run sheet', 'print']], sm: [[Download, 'Export CSV', 'export'], [BarChart3, 'Dispatch report', 'report:Dispatch report']] },
  ],
  parts: [
    { label: 'Stores', lg: [[PackageMinus, 'Issue to a\njob card', 'issuePart'], [Package, 'New\nline', 'dlg:part']], sm: [[SlidersHorizontal, 'Adjust stock', 'adjustStock'], [Boxes, 'Movement and value', 'partsView:movement'], [AlertTriangle, 'Below reorder', 'partsView:reorder']] },
    { label: 'Replenishment', lg: [[ShoppingCart, 'Raise an\norder', 'orderPart'], [PackageCheck, 'Receive', 'goto:procurement']], sm: [[Building2, 'Suppliers', 'goto:procurement'], [Repeat, 'Reorder proposal', 'reorderProposal']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe pick list', 'print']], sm: [[Download, 'Export CSV', 'export'], [FileText, 'Stock report', 'report:Stock report']] },
  ],
  tyres: [
    { label: 'Register', lg: [[CircleDot, 'Fit a\ntyre', 'dlg:fitTyre'], [Ruler, 'Record\ntread', 'logTread']], sm: [[Trash2, 'Scrap the tyre', 'scrapTyre'], [AlertTriangle, 'Below the limit', 'tyresView:legal'], [Coins, 'Cost per kilometre', 'tyresView:cost']] },
    { label: 'Vehicle', lg: [[Truck, 'Open the\nvehicle', 'openTyreVehicle']], sm: [[Wrench, 'Raise a work order', 'raiseWO'], [ClipboardCheck, 'Pre-use check', 'startInspection']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe card', 'print']], sm: [[Download, 'Export CSV', 'export'], [FileText, 'Tyre report', 'report:Tyre report']] },
  ],
  fuel: [
    { label: 'Transactions', lg: [[Fuel, 'Capture\na fill', 'dlg:fuel'], [CheckCircle2, 'Verify', 'verifyFuel']], sm: [[AlertTriangle, 'Clear an exception', 'clearException'], [Gauge, 'Consumption', 'fuelView:consumption'], [Truck, 'Open the vehicle', 'openFuelVehicle']] },
    { label: 'Control', lg: [[Percent, 'Variance\nthreshold', 'goto:settings']], sm: [[Plug, 'Card import', 'goto:admin'], [Coins, 'Diesel price', 'goto:settings'], [History, 'Audit the card', 'goto:audit']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe register', 'print']], sm: [[Download, 'Export CSV', 'export'], [FileText, 'Fuel report', 'report:Fuel report']] },
  ],
  telematics: [
    { label: 'Events', lg: [[Zap, 'Open\nevents', 'telematicsView:events'], [CheckCircle2, 'Acknowledge\nall', 'ackAll']], sm: [[Gauge, 'Operator behaviour', 'telematicsView:behaviour'], [User, 'Open the operator', 'openEventDriver'], [Timer, 'Idling report', 'report:Idling report']] },
    { label: 'Units', lg: [[Radio, 'Unit\nstatus', 'telematicsView:units'], [MapPin, 'Live\nmap', 'liveMap']], sm: [[Signal, 'Offline units', 'offlineUnits'], [Plug, 'Integration health', 'goto:admin'], [RefreshCw, 'Poll now', 'refresh']] },
    { label: 'Output', lg: [[Printer, 'Print', 'print']], sm: [[Download, 'Export CSV', 'export']] },
  ],
  documents: [
    { label: 'Register', lg: [[Upload, 'Upload a\ndocument', 'dlg:document'], [BadgeCheck, 'Verify', 'verifyDoc']], sm: [[CalendarClock, 'Expiring soon', 'documentsView:expiring'], [Files, 'By kind', 'documentsView:kinds'], [Download, 'Download the file', 'download']] },
    { label: 'Renewals', lg: [[CalendarPlus, 'Book a\nrenewal', 'bookRenewal']], sm: [[Bell, 'Expiry reminders', 'alerts'], [Mail, 'Notify the holder', 'email'], [ShieldCheck, 'Compliance board', 'goto:compliance']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe register', 'print']], sm: [[Download, 'Export CSV', 'export'], [FileText, 'Document report', 'report:Document report']] },
  ],
  incidents: [
    { label: 'Investigation', lg: [[ShieldAlert, 'Log an\nincident', 'dlg:incident'], [FileCheck2, 'Lodge a\nclaim', 'lodgeClaim']], sm: [[Play, 'Move to investigating', 'incidentStatus:Investigating'], [CheckCircle2, 'Close it', 'incidentStatus:Closed'], [BarChart3, 'Analysis', 'incidentsView:analysis']] },
    { label: 'Consequence', lg: [[Wrench, 'Raise a\nwork order', 'raiseWOFromIncident'], [Truck, 'Ground the\nvehicle', 'groundFromIncident']], sm: [[User, 'Open the operator', 'openIncidentDriver'], [Gauge, 'Behaviour score', 'goto:telematics'], [HeartPulse, 'Injury report', 'report:Incident report']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe file', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Send to the insurer', 'email']] },
  ],
  costs: [
    { label: 'Analysis', lg: [[Coins, 'Cost per\nvehicle', 'costsView:vehicles'], [Scale, 'Budget vs\nactual', 'costsView:budget']], sm: [[Landmark, 'By site and class', 'costsView:sites'], [TrendingUp, 'Replacement case', 'goto:contracts'], [Truck, 'Open the vehicle', 'openCostVehicle']] },
    { label: 'Control', lg: [[Wallet, 'Set a\nbudget', 'dlg:budget']], sm: [[Fuel, 'Fuel spend', 'goto:fuel'], [Wrench, 'Workshop spend', 'goto:workshop'], [CircleDot, 'Tyre spend', 'goto:tyres']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe cost report', 'print']], sm: [[Download, 'Export CSV', 'export'], [FileText, 'Cost report', 'report:Cost report']] },
  ],
  procurement: [
    { label: 'Orders', lg: [[ShoppingCart, 'Raise an\norder', 'dlg:po'], [Send, 'Send to\nsupplier', 'poStatus:Sent']], sm: [[PackageCheck, 'Receive into stock', 'poStatus:Received'], [CheckCircle2, 'Approve', 'poStatus:Sent'], [Package, 'Open the stores', 'goto:parts']] },
    { label: 'Supplier invoices', lg: [[FileText, 'Supplier\ninvoices', 'procurementView:invoices'], [CheckCircle2, 'Approve', 'sinStatus:Approved']], sm: [[CircleAlert, 'Raise a query', 'sinStatus:Query'], [Banknote, 'Mark paid', 'sinStatus:Paid'], [Building2, 'Suppliers', 'procurementView:suppliers']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe order', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email the supplier', 'email']] },
  ],
  billing: [
    { label: 'Invoices', lg: [[Receipt, 'Raise an\ninvoice', 'dlg:invoice'], [Banknote, 'Receipt a\npayment', 'recordPayment']], sm: [[CircleDollarSign, 'Ready to bill', 'billingView:unbilled'], [Clock, 'Aging and customers', 'billingView:aging'], [Route, 'Open the job', 'openInvoiceJob']] },
    { label: 'Collection', lg: [[Mail, 'Send a\nreminder', 'email']], sm: [[Printer, 'Print a statement', 'print'], [FileText, 'Debtors report', 'report:Debtors report']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe invoice', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email the customer', 'email']] },
  ],
  contracts: [
    { label: 'Assets', lg: [[Landmark, 'Contract\nregister', 'contractsView:register'], [TrendingUp, 'Replacement\ncase', 'contractsView:replacement']], sm: [[Building2, 'By financier', 'contractsView:financiers'], [Repeat, 'Renew or settle', 'renewContract'], [Truck, 'Open the vehicle', 'openContractVehicle']] },
    { label: 'Finance', lg: [[CreditCard, 'Instalment\nschedule', 'schedule']], sm: [[Coins, 'Cost per vehicle', 'goto:costs'], [Plug, 'Financier feed', 'goto:admin']] },
    { label: 'Output', lg: [[Printer, 'Print\nthe schedule', 'print']], sm: [[Download, 'Export CSV', 'export'], [FileText, 'Asset report', 'report:Asset register'] ] },
  ],
  admin: [
    { label: 'Platform', lg: [[Server, 'Scheduled\njobs', 'adminView:jobs'], [Plug, 'Integrations', 'adminView:integrations']], sm: [[RefreshCw, 'Run a job now', 'runJob'], [Database, 'Backups', 'backups'], [History, 'Audit trail', 'goto:audit']] },
    { label: 'Access', lg: [[UserCog, 'Roles and\npermissions', 'adminView:roles'], [CheckSquare, 'Approvals', 'adminView:approvals']], sm: [[CheckCircle2, 'Approve', 'approve:Approved'], [X, 'Decline', 'approve:Declined'], [Users, 'Open the people register', 'goto:users']] },
    { label: 'Output', lg: [[Printer, 'Print', 'print']], sm: [[Download, 'Export CSV', 'export'], [Settings, 'Settings', 'goto:settings']] },
  ],
  dashboard: [
    { label: 'Period', lg: [[RefreshCw, 'Refresh\ndata', 'refresh'], [CalendarPlus, 'Change\nperiod', 'period']], sm: [[Building2, 'Site roll-up', 'goto:analytics'], [Gauge, 'Targets', 'goto:settings'], [Bell, 'Alert rules', 'alerts']] },
    { label: 'Operations', lg: [[Route, 'Dispatch', 'goto:dispatch'], [Truck, 'Fleet', 'goto:fleet']], sm: [[ClipboardCheck, 'Inspections', 'goto:inspections'], [Wrench, 'Workshop', 'goto:workshop'], [Users, 'Operators', 'goto:users']] },
    { label: 'Cost and risk', lg: [[Coins, 'Costs', 'goto:costs'], [Fuel, 'Fuel', 'goto:fuel']], sm: [[ShieldAlert, 'Incidents', 'goto:incidents'], [ShieldCheck, 'Compliance', 'goto:compliance'], [Receipt, 'Billing', 'goto:billing']] },
    { label: 'Share', lg: [[Printer, 'Print\nboard', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email board', 'email'], [Share2, 'Send to a site', 'email']] },
  ],
  inspections: [
    { label: 'Capture', lg: [[ClipboardCheck, 'Start\ninspection', 'startInspection'], [FileCheck2, 'Choose\nform', 'inspView:forms']], sm: [[CheckSquare, 'Sign off', 'signOff'], [Eye, 'Open sheet', 'openInspection'], [X, 'Return to operator', 'rejectInspection']] },
    { label: 'Defects', lg: [[AlertTriangle, 'Defect\nregister', 'inspView:defects'], [Clock, 'Lapsed\nconcessions', 'lapsedConcessions']], sm: [[CheckSquare, 'Sign concession', 'signConcession'], [Wrench, 'Raise work order', 'raiseWO'], [CheckCircle2, 'Close defect', 'closeDefect']] },
    { label: 'Forms', lg: [[FileCheck2, 'Form\nregister', 'inspView:forms']], sm: [[Repeat, 'New revision', 'reviseForm'], [CheckCircle2, 'Publish form', 'publishForm'], [Files, 'Duplicate', 'duplicateForm']] },
    { label: 'Output', lg: [[Printer, 'Print\nsheet', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email the sheet', 'email']] },
  ],
  fleet: [
    { label: 'Vehicles', lg: [[Truck, 'New\nvehicle', 'dlg:vehicle'], [Car, 'Assign to\noperator', 'assignVehicle']], sm: [[Pencil, 'Edit vehicle', 'editVehicle'], [Gauge, 'Update odometer', 'logOdo'], [CarFront, 'Unassign', 'unassignVehicle']] },
    { label: 'Status', lg: [[XCircle, 'Take off\nroad', 'ground'], [RotateCcw, 'Return to\nservice', 'returnService']], sm: [[Wrench, 'Book a service', 'bookService'], [ClipboardCheck, 'Pre-use check', 'startInspection'], [CircleAlert, 'Open defects', 'inspView:defects']] },
    { label: 'Running costs', lg: [[Coins, 'Cost per\nkilometre', 'goto:costs'], [Fuel, 'Fuel\nhistory', 'goto:fuel']], sm: [[CircleDot, 'Tyres fitted', 'goto:tyres'], [Landmark, 'Finance contract', 'goto:contracts'], [Radio, 'Telematics unit', 'goto:telematics']] },
    { label: 'Compliance', lg: [[BadgeCheck, 'COF\nregister', 'goto:compliance']], sm: [[CalendarClock, 'Service due list', 'serviceDue'], [Files, 'Documents held', 'goto:documents'], [Upload, 'Upload document', 'upload']] },
    { label: 'Output', lg: [[Printer, 'Print\ncard', 'print']], sm: [[Download, 'Export CSV', 'export'], [BarChart3, 'Fleet report', 'report:Fleet status report']] },
  ],
  workshop: [
    { label: 'Work orders', lg: [[Wrench, 'Raise work\norder', 'raiseWO'], [Play, 'Move to\nin progress', 'woStatus:In progress']], sm: [[Package, 'Awaiting parts', 'woStatus:Awaiting parts'], [CheckCircle2, 'Complete', 'woStatus:Completed'], [Eye, 'Open the defect', 'openWODefect']] },
    { label: 'Job card', lg: [[CheckSquare, 'Authorise', 'authoriseWO'], [PackageMinus, 'Issue\nparts', 'issuePart']], sm: [[Clock, 'Book labour', 'bookLabour'], [ShoppingCart, 'Order parts', 'orderPart'], [Coins, 'Job cost', 'goto:costs']] },
    { label: 'Vehicle', lg: [[Truck, 'Open the\nvehicle', 'openWOVehicle']], sm: [[RotateCcw, 'Return to service', 'returnService'], [ClipboardCheck, 'Re-inspect', 'startInspection'], [Wrench, 'Service planner', 'workshopView:planner']] },
    { label: 'Output', lg: [[Printer, 'Print\njob card', 'print']], sm: [[Download, 'Export CSV', 'export'], [FileText, 'Workshop report', 'report:Workshop report']] },
  ],
  users: [
    { label: 'People', lg: [[UserPlus, 'New\nuser', 'dlg:user'], [Pencil, 'Edit\nuser', 'editUser']], sm: [[IdCard, 'Open record', 'openUser'], [KeyRound, 'Reset password', 'resetPassword'], [ShieldCheck, 'Enforce 2FA', 'enforceMfa']] },
    { label: 'Lifecycle', lg: [[UserX, 'Suspend\nuser', 'suspendUser'], [Trash2, 'Delete\nuser', 'deleteUser']], sm: [[BadgeCheck, 'Reactivate', 'reactivateUser'], [Network, 'Change supervisor', 'editUser'], [Mail, 'Resend invitation', 'resendInvite']] },
    { label: 'Assignment', lg: [[Car, 'Assign\nvehicle', 'assignUserVehicle'], [CarFront, 'Unassign\nvehicle', 'unassignUserVehicle']], sm: [[UsersRound, 'Bulk assign', 'bulkAssign'], [Network, 'Open hierarchy', 'goto:hierarchy'], [Truck, 'Open the vehicle', 'openUserVehicle']] },
    { label: 'Performance', lg: [[Gauge, 'Behaviour\nscore', 'goto:telematics'], [Route, 'Jobs run', 'goto:dispatch']], sm: [[Timer, 'Hours this week', 'usersView:hours'], [ClipboardCheck, 'Inspection history', 'goto:inspections'], [ShieldAlert, 'Incidents', 'goto:incidents']] },
    { label: 'Certificates', lg: [[BadgeCheck, 'COF\nregister', 'goto:compliance']], sm: [[CalendarClock, 'Expiry reminders', 'alerts'], [Files, 'Documents held', 'goto:documents'], [Upload, 'Upload certificate', 'upload']] },
    { label: 'Output', lg: [[Printer, 'Print\nlist', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email selected', 'email']] },
  ],
  hierarchy: [
    { label: 'Structure', lg: [[Network, 'Change\nsupervisor', 'editUser'], [UserPlus, 'New\nuser', 'dlg:user']], sm: [[Users, 'Open the person', 'goto:users'], [UserX, 'Detach user', 'editUser'], [RefreshCw, 'Rebuild tree', 'refresh']] },
    { label: 'Gaps', lg: [[CircleAlert, 'Unassigned\nitems', 'unassigned']], sm: [[Car, 'Assign vehicle', 'assignUserVehicle'], [UsersRound, 'Bulk assign', 'bulkAssign']] },
    { label: 'Output', lg: [[Printer, 'Print\nchart', 'print']], sm: [[Download, 'Export CSV', 'export']] },
  ],
  compliance: [
    { label: 'Certificates', lg: [[BadgeCheck, 'COF\nregister', 'cofRegister'], [Upload, 'Upload\ncertificate', 'upload']], sm: [[Bell, 'Expiry reminders', 'alerts'], [Mail, 'Notify the operator', 'email'], [CalendarPlus, 'Book a renewal', 'bookRenewal']] },
    { label: 'Defects', lg: [[AlertTriangle, 'No-go\nregister', 'noGoRegister'], [Clock, 'Lapsed\nconcessions', 'lapsedConcessions']], sm: [[Wrench, 'Raise work order', 'raiseWO'], [CheckCircle2, 'Close defect', 'closeDefect'], [RotateCcw, 'Return to service', 'returnService']] },
    { label: 'Assurance', lg: [[ShieldCheck, 'Compliance\nreport', 'report:Compliance report']], sm: [[History, 'Audit trail', 'goto:audit'], [Download, 'Export CSV', 'export'], [Printer, 'Print', 'print']] },
  ],
  audit: [
    { label: 'Trail', lg: [[Search, 'Search\ntrail', 'searchAudit'], [Filter, 'Filter\nactions', 'filterAudit']], sm: [[Calendar, 'Date range', 'dateRange'], [User, 'By user', 'byUser'], [FilterX, 'Clear filters', 'clearFilters']] },
    { label: 'Governance', lg: [[FileText, 'Retention\npolicy', 'retention']], sm: [[Lock, 'Verify integrity', 'verify'], [Download, 'Export audit', 'export'], [Printer, 'Print', 'print']] },
  ],
  profile: [
    { label: 'Company', lg: [[Pencil, 'Edit\nprofile', 'editCompany'], [IdCard, 'Contact\ndetails', 'editCompany']], sm: [[UserPlus, 'Add user', 'dlg:user'], [Truck, 'Add vehicle', 'dlg:vehicle'], [Upload, 'Upload documents', 'upload']] },
    { label: 'Subscription', lg: [[Award, 'Change\nplan', 'upgrade'], [LayoutGrid, 'Manage\nmodules', 'modules']], sm: [[Receipt, 'Billing and invoices', 'billing'], [CreditCard, 'Payment method', 'billing'], [Download, 'Download invoice', 'export']] },
    { label: 'Output', lg: [[Printer, 'Print\nprofile', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email profile', 'email']] },
  ],
  reports: [
    { label: 'Operations', lg: [[ClipboardCheck, 'Inspection\nreport', 'report:Inspection report'], [Truck, 'Fleet status\nreport', 'report:Fleet status report']], sm: [[Users, 'User activity', 'report:User activity report'], [Wrench, 'Workshop report', 'report:Workshop report']] },
    { label: 'Safety', lg: [[ShieldCheck, 'Compliance\nreport', 'report:Compliance report'], [AlertTriangle, 'Defect\nhistory', 'report:Defect history']], sm: [[BadgeCheck, 'COF expiry', 'report:COF expiry report'], [Clock, 'Lapsed concessions', 'lapsedConcessions']] },
    { label: 'Output', lg: [[Printer, 'Print\nreport', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email report', 'email'], [Repeat, 'Schedule report', 'schedule']] },
  ],
  analytics: [
    { label: 'Views', lg: [[BarChart3, 'Results\nbreakdown', 'refresh'], [TrendingUp, 'Trend\nanalysis', 'refresh']], sm: [[Percent, 'Pass rate', 'refresh'], [Clock, 'Aging profile', 'refresh'], [PieChart, 'By site', 'refresh']] },
    { label: 'Period', lg: [[CalendarPlus, 'Change\nperiod', 'period']], sm: [[RefreshCw, 'Refresh data', 'refresh'], [FilterX, 'Clear filters', 'clearFilters']] },
    { label: 'Output', lg: [[Printer, 'Print\ncharts', 'print']], sm: [[Download, 'Export CSV', 'export'], [Mail, 'Email analysis', 'email']] },
  ],
  settings: [
    { label: 'Platform', lg: [[SlidersHorizontal, 'General\noptions', 'refresh'], [Palette, 'Branding', 'branding']], sm: [[Globe, 'Localisation', 'refresh'], [Mail, 'Email templates', 'templates'], [Plug, 'Integrations', 'integrations']] },
    { label: 'Inspection rules', lg: [[ClipboardCheck, 'Capture\nrules', 'refresh']], sm: [[Clock, 'Go-but window', 'refresh'], [Gauge, 'Targets', 'refresh'], [Bell, 'Alert rules', 'alerts']] },
    { label: 'Security', lg: [[ShieldCheck, 'Access\npolicy', 'refresh'], [KeyRound, 'Roles and\npermissions', 'roles']], sm: [[Lock, 'Password policy', 'refresh'], [Smartphone, 'Two-factor', 'enforceMfa'], [History, 'Login audit', 'goto:audit']] },
    { label: 'Data', lg: [[Database, 'Backups', 'backups']], sm: [[Download, 'Export data', 'export'], [Upload, 'Import data', 'import'], [FileText, 'Retention policy', 'retention']] },
  ],
  view: [
    { label: 'Layout', lg: [[PanelLeft, 'Navigation\npane', 'toggleNav'], [Rows3, 'Row\ndensity', 'density']], sm: [[Columns3, 'Reading pane', 'togglePane'], [ChevronsUp, 'Collapse ribbon', 'collapse'], [Maximize, 'Full screen', 'fullscreen']] },
    { label: 'Data', lg: [[RefreshCw, 'Refresh', 'refresh']], sm: [[FilterX, 'Clear filters', 'clearFilters'], [Download, 'Export CSV', 'export'], [Printer, 'Print', 'print']] },
    { label: 'Window', lg: [[Settings, 'Options', 'goto:settings']], sm: [[Bell, 'Notifications', 'alerts'], [Info, 'About SafeNexus', 'about']] },
  ],
};

export const JUMPS = [
  ['Awaiting sign-off', ClipboardCheck, 'goto:inspections'],
  ['Grounded vehicles', AlertTriangle, 'goto:fleet'],
  ['Lapsed concessions', Clock, 'lapsedConcessions'],
  ['Open work orders', Wrench, 'goto:workshop'],
  ['Fuel exceptions', Fuel, 'fuelView:exceptions'],
  ['Tyres below the limit', CircleDot, 'tyresView:legal'],
  ['Parts below reorder', Package, 'partsView:reorder'],
  ['Certificates expiring', Files, 'documentsView:expiring'],
  ['Open incidents', ShieldAlert, 'goto:incidents'],
  ['Overdue invoices', Receipt, 'goto:billing'],
  ['Awaiting approval', CheckSquare, 'adminView:approvals'],
  ['Audit trail', History, 'goto:audit'],
];

export const MESSAGES = {
  refresh: 'Data refreshed from SAFENEXUS-SQL01.', save: 'Workspace saved.',
  undo: 'Last action undone.', redo: 'Action reapplied.',
  print: 'Sent to the print queue.', export: 'Export written to CSV.',
  email: 'Draft opened in the mail client.', period: 'Period changed to June 2026.',
  targets: 'Compliance target held at 90%.', alerts: 'Alert rules opened.',
  signOff: 'Sign-off recorded against the selected inspection.',
  openInspection: 'Inspection #2120352 opened.', addNote: 'Note added to the inspection.',
  escalate: 'Escalated to the safety officer.', reject: 'Capture rejected and returned to the operator.',
  assignVehicle: 'Vehicle assignment recorded.', unassignVehicle: 'Vehicle returned to the pool.',
  assignSupervisor: 'Supervisor assignment recorded.', bulkAssign: 'Bulk assignment queued for 8 operators.',
  moveUnder: 'User moved in the hierarchy.', detach: 'User detached from the hierarchy.',
  unassigned: '3 operators and 8 vehicles are unassigned.',
  editUser: 'Editing the selected user.', editVehicle: 'Editing the selected vehicle.',
  editCompany: 'Editing the company profile.', resetPassword: 'Password reset link emailed.',
  enforceMfa: 'Two-factor authentication enforced for administrators.',
  disableUser: 'User disabled and sessions revoked.', suspend: 'Company suspended pending review.',
  deleteCompany: 'Deletion requires a second administrator to approve.',
  upgrade: 'Enterprise upgrade quote generated.', modules: 'Module manager opened.',
  billing: 'Billing and invoices opened.', bookService: 'Service booked with the workshop.',
  serviceDue: '4 vehicles are due for a service.', licences: '2 licence renewals fall due this month.',
  returnService: 'Vehicle returned to service after inspection.',
  ground: 'Vehicle grounded and removed from the roster.',
  raiseDefect: 'Defect raised against the vehicle.', closeDefect: 'Defect closed and signed off.',
  logFuel: 'Fuel entry captured.', logOdo: 'Odometer reading updated.',
  shiftPlan: 'Shift plan opened.', recurring: 'Recurring pre-use checks configured.',
  cofRegister: 'COF register opened — 14 expiring within 90 days.',
  noGoRegister: '7 open no-go defects across the platform.',
  goButAging: '23 go-but items are older than 20 days.',
  upload: 'Document uploaded and queued for verification.', bookRenewal: 'COF renewal booked.',
  searchAudit: 'Audit search opened.', filterAudit: 'Audit filter applied.',
  dateRange: 'Date range set to the last 7 days.', byUser: 'Filtered by user.',
  verify: 'Audit chain verified — no gaps found.', retention: 'Retention held at 7 years, append-only.',
  clearFilters: 'Filters cleared.', columns: 'Column chooser opened.',
  fullscreen: 'Full screen toggled.', saveSettings: 'Settings saved.',
  branding: 'Branding options opened.', templates: 'Email templates opened.',
  integrations: 'Integration catalogue opened.', roles: 'Roles and permissions opened.',
  backups: 'Last backup completed 18 Jun 2026 at 02:00.', import: 'Import wizard opened.',
  account: 'Signed in as Kobus van der Merwe (Administrator).',
  about: 'SafeNexus ERP 2026.6 · build 4812 · SAFENEXUS-SQL01.',
  schedule: 'Report scheduled for the first of each month.',
  newForm: 'Form builder opened — start from a published form or a blank sheet.',
  duplicateForm: 'Form duplicated as a draft.',
  unassigned: 'Operators without a supervisor are listed under Gaps in the line.',
  cofRegister: 'Certificate register opened.',
  noGoRegister: 'Filtered to open no-go defects.',
  serviceDue: 'Vehicles within the service warning distance are listed.',
  licences: 'Licence renewals due this month are listed.',
  resendInvite: 'Invitation resent.',
  changeSupervisor: 'Supervisor changed.',
  upload: 'Certificate uploaded and queued for verification.',
};
